threads: 5                                           # THREADS Amount
solver: ""                                           # CAPSOLVER , CAPBYPASS
capKey: ""                                           # CAPTCHA KEY  
